### ISSUE TITLE
mov-cli-films is no more.

### ISSUE THREAD

**Issue by Fraei2** [JDALab/film-central#1]
If `mov-cli-films` is still set in your config as the film scraper, now it's time to switch to `film-central`.

```toml
[mov-cli.plugins]
films = "film-central"
```
